from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)

from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch

import io


def generate_pdf(financial_data, score, status, recommendations):

    buffer = io.BytesIO()

    doc = SimpleDocTemplate(buffer)

    styles = getSampleStyleSheet()

    elements = []

    elements.append(
        Paragraph(
            "<b>FinSight Financial Report</b>",
            styles["Title"]
        )
    )

    elements.append(Spacer(1, 0.3 * inch))

    elements.append(
        Paragraph(
            "Generated using FinSight",
            styles["Normal"]
        )
    )

    elements.append(Spacer(1, 0.25 * inch))
    table_data = [
        ["Financial Metric", "Value"]
    ]

    for key, value in financial_data.items():

        table_data.append(
            [
                key,
                f"₹ {value:,.2f}"
            ]
        )

    table = Table(table_data)

    table.setStyle(

        TableStyle(

            [

                ("BACKGROUND", (0, 0), (-1, 0), colors.darkblue),

                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

                ("GRID", (0, 0), (-1, -1), 1, colors.grey),

                ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),

                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),

                ("BOTTOMPADDING", (0, 0), (-1, 0), 10),

                ("ALIGN", (0, 0), (-1, -1), "CENTER")

            ]

        )

    )

    elements.append(table)

    elements.append(Spacer(1, 0.3 * inch))

    elements.append(
        Paragraph(
            "<b>Financial Health Summary</b>",
            styles["Heading2"]
        )
    )

    elements.append(
        Paragraph(
            f"<b>Health Score:</b> {score}/100",
            styles["Normal"]
        )
    )

    elements.append(
        Paragraph(
            f"<b>Overall Status:</b> {status}",
            styles["Normal"]
        )
    )

    elements.append(Spacer(1, 0.25 * inch))

    elements.append(
        Paragraph(
            "<b>Recommendations</b>",
            styles["Heading2"]
        )
    )

    for recommendation in recommendations:

        elements.append(
            Paragraph(
                f"• {recommendation}",
                styles["Normal"]
            )
        )

    elements.append(Spacer(1, 0.3 * inch))
    elements.append(
        Paragraph(
            "<br/><b>Generated by FinSight</b>",
            styles["Heading3"]
        )
    )

    elements.append(
        Paragraph(
            "Developed by Aayush Minglani",
            styles["Normal"]
        )
    )

    doc.build(elements)
    print("PDF GENERATED")
    print(len(buffer.getvalue()))

    pdf = buffer.getvalue()

    buffer.close()

    return pdf  